const incomeList = [{ 'class': 'icon-icon-test', 'label': '饮食' },
{ 'class': 'icon-gouwuche', 'label': '购物' },
{ 'class': 'icon-jiatingqingji', 'label': '日用' },
{ 'class': 'icon-shengxianshuiguo', 'label': '生鲜水果' },
{ 'class': 'icon-hanbao', 'label': '零食' },
{ 'class': 'icon-shipinyinliao', 'label': '饮料' },
{ 'class': 'icon-shengriliwu', 'label': '礼物' },
{ 'class': 'icon-Txu', 'label': '服装' },
{ 'class': 'icon-kouhong', 'label': '化妆品' },
{ 'class': 'icon-nvbao', 'label': '包包' },
{ 'class': 'icon-zuanshi', 'label': '首饰' },
{ 'class': 'icon-quanleichongwubaozhang', 'label': '宠物' },
{ 'class': 'icon-bingxiang', 'label': '家具' },
{ 'class': 'icon-leqi', 'label': '乐器' },
{ 'class': 'icon-chongzhi', 'label': '充值' },
{ 'class': 'icon-dianhua', 'label': '电话' },
{ 'class': 'icon-yanjiuyan', 'label': '烟酒' },
{ 'class': 'icon-yaopin', 'label': '医疗' },
{ 'class': 'icon-bangqiu', 'label': '运动' },
{ 'class': 'icon-laoren', 'label': '长辈' },
{ 'class': 'icon-jiachang', 'label': '父母' },
{ 'class': 'icon-mn_pengyou_fill', 'label': '朋友聚餐' },
{ 'class': 'icon-naiping', 'label': '子女' },
{ 'class': 'icon-tushu', 'label': '学习' },
{ 'class': 'icon-caipiao', 'label': '彩票' },
{ 'class': 'icon-aixinjuanzeng', 'label': '爱心捐赠' },
{ 'class': 'icon-feiji', 'label': '旅行' },
{ 'class': 'icon-solid-home', 'label': '房租' },
{ 'class': 'icon-weixiu', 'label': '维修' },
{ 'class': 'icon-31huabei', 'label': '花呗' },
{ 'class': 'icon-tesefuwu', 'label': '特色服务' },
{ 'class': 'icon-else', 'label': '其它' },
];

var expendList = [
  { 'class': 'icon-gouwuche', 'label': '购物' },
  { 'class': 'icon-jiatingqingji', 'label': '日用' },
  { 'class': 'icon-shengxianshuiguo', 'label': '生鲜水果' },
  { 'class': 'icon-hanbao', 'label': '零食' },
  { 'class': 'icon-shipinyinliao', 'label': '饮料' },
]

module.exports = { incomeList, expendList }